### ISSUE TITLE
Analyzer raises DAP019 Sql Parameters error for parameters used inside query only

### ISSUE THREAD

**Issue by pmccowat** [DapperLib/DapperAOT#44]
In a few Dapper SQL queries, I have query level parameters which are used as variables inside the query scope and don't require any values to be passed in as arguments to the Dapper in methods like QueryAsync.
  
    DECLARE @ActiveWidgets TABLE  (Id int)
    INSERT @ActiveWidgets SELECT Id FROM Widgets WHERE Active = 1

This is raising the error DAP019	SQL parameters were detected, but no parameters are being supplied

**Comment by mgravell** [comment]
That's weird - we explicitly consider table variables, and have tests for it. I'll check, though.

**Comment by mgravell** [comment]
Existing test to check: https://github.com/DapperLib/DapperAOT/blob/bad0efdf61a897bc0d29aa820e17cf6f1ec3628b/test/Dapper.AOT.Test/TSqlParserTests.cs#L185

**Comment by mgravell** [comment]
right; so this only happens in the fallback case i.e. when the connection type is not `SqlConnection`; if it knows you're using TSQL, this is not an issue - it uses the advanced TSQL parser and applies (much) more logic.

If you're using DapperAOT there is also a hint to specify this; I am going to improve the message *and* add a csproj-level configuration to opt in to TSQL

**Comment by pmccowat** [comment]
In this case, I was using `DbConnection` from EF6 

`_context.Database.Connection.QueryAsync`

**Comment by mgravell** [comment]
OK, I've updated the rule to include a help link that explains a bunch:

![image](https://github.com/DapperLib/DapperAOT/assets/17328/1dac8834-dd80-49d1-83bb-be4109f894d1)

That link [goes here](https://aot.dapperlib.dev/rules/DAP019)

I'm going to close this one and re-open a new ticket to support project level SQL syntax specification

**Comment by mgravell** [comment]
https://github.com/DapperLib/DapperAOT/issues/47
