### ISSUE TITLE
Red Underlining is still shown after error resolve and code rebuilt

### ISSUE THREAD

**Issue by oriches** [DapperLib/DapperAOT#49]
Fixed a couple of highlighted errors, rebuilt the code and the red underlining of the sql query string is still visible.

Note: Errors are gone from Output & Error List windows.

**Comment by mgravell** [comment]
That isn't something I can do anything about - we just report the diagnostics (or lack there-of); what the IDE does with them: is up to the IDE. If it is glitching, it may improve when we complete https://github.com/DapperLib/DapperAOT/issues/47, but... 🤷
