### ISSUE TITLE
Possibly false positive DAP231 SELECT for single row without WHERE or (TOP and ORDER BY) (L1 C1)

### ISSUE THREAD

**Issue by alex-belikov** [DapperLib/DapperAOT#52]
I'm getting this warning for query like this:

select HasRows = case when exists (select top 1 1 from MyTable) then 1 else 0 end

I believe the warning tried to prevent other issues, which might not be applicable for this query.

**Comment by alex-belikov** [comment]
Updating with full example:
```
public async Task<bool> HasRecordsExample()
{
    return await Conn().QueryFirstAsync<bool>(
        "select HasRecords = case when exists (select top 1 1 from MyTable) then 1 else 0 end");
}
```

**Comment by mgravell** [comment]
great report, thanks! fixed in the working branch, but it'll probably be a few days before I'm ready to merge that - a bit of a major refactor to get as much as possible off the generator pipe
