### ISSUE TITLE
Will DapperAOT support protobuf-net?

### ISSUE THREAD

**Issue by shps951023** [DapperLib/DapperAOT#6]
@mgravell  

Hi, I like DapperAOT using Roslyn generator idea to remove runtime emit/reflection dependencies, and generate mapping code at build, it's awesome!  
Will it support protobuf?

**Comment by mgravell** [comment]
Happy to discuss it if you like, but: I have no idea what this means

**Comment by mgravell** [comment]
I see Dapper and protobuf-net as completely separate tools, with no
particular overlap. There has never been any specific
Dapper-plus-protobuf-net plan, so there is nothing to stop. There are plans
for both of them in isolation to make better use of generators, but both of
those plans need my time, which is the limiting factor.

If you feel there's a scenario that needs attention in a composite way, I'm
happy to discuss it. But I don't have a list of such crossover scenarios
currently.

**Comment by shps951023** [comment]
@mgravell 
Sorry, I know my knowledge is wrong, so I close this question.  
I like DapperAOT idea and I'm reading it now.
