### ISSUE TITLE
[DAP025] False positive: SELECT INTO

### ISSUE THREAD

**Issue by dotTrench** [DapperLib/DapperAOT#79]
**Describe the bug**
When using `SqlConnection` and selecting data from one table into another using `ExecuteAsync` a false DAP025 warning is triggered.  

Dapper.Advisor: 1.0.10

**To Reproduce**
```csharp
// DAP025: The command has a query that will be ignored
public static async Task SelectInto(SqlConnection connection) =>
    await connection.ExecuteAsync("SELECT [Test] INTO #MyTemporaryTable FROM MyTable");

```

**Comment by mgravell** [comment]
https://github.com/DapperLib/DapperAOT/releases/tag/1.0.16
