### ISSUE TITLE
Is DapperAOT used in the StackOverflow?

### ISSUE THREAD

**Issue by Jack005566** [DapperLib/DapperAOT#8]
It's good project, but there's a question : 'Is DapperAOT used in the StackOverflow?'
Or it's experimental tool?

**Comment by NickCraver** [comment]
Hey Jack, this is an experiment so far. When Marc and I hopefully have time, what goes into v3 or becomes a side-by-side can be figured out, lots of non-trivial work there.

**Comment by Jack005566** [comment]
@NickCraver  Thanks!
