### ISSUE TITLE
[DAP226] False positive: DATEADD

### ISSUE THREAD

**Issue by dotTrench** [DapperLib/DapperAOT#80]
**Describe the bug**
When using `SqlConnection` and querying data using the built-in MSSQL-function `DATEADD` parameter `datepart` is falsely identified as a table column causing a false `DAP226` warning when used in a query with joins.

Dapper.Advisor: 1.0.10

**To Reproduce**
```csharp
// DAP226: FROM expressions with multiple elements should qualify all columns; it is unclear where 'YEAR' is located
public static async Task DateAddWithJoin(SqlConnection connection) =>
    await connection.QueryAsync(
        """
        SELECT DATEADD(YEAR, 1, t.Year) AS NextYear
        FROM MyTable t
        JOIN MyOtherTable o ON o.Id = t.Id
        """
    );
```

**Comment by mgravell** [comment]
Fair. Should be a very simple fix!

**Comment by mgravell** [comment]
https://github.com/DapperLib/DapperAOT/releases/tag/1.0.16
