### ISSUE TITLE
[DAP231] False positive: Full table aggregation

### ISSUE THREAD

**Issue by dotTrench** [DapperLib/DapperAOT#81]
**Describe the bug**

When using an aggregation function e.g. MIN/MAX an a full table a false `DAP231` warning is given 

Dapper.Advisor: 1.0.10

**To Reproduce**
```csharp
// DAP231: SELECT for single row without WHERE or (TOP and ORDER BY)
public static async Task<int> SelectMax(SqlConnection connection) =>
    await connection.QueryFirstOrDefaultAsync<int>("SELECT MAX(SomeColumn) FROM MyTable");
```

**Comment by mgravell** [comment]
D'oh, I should have thought of that. Thanks, great example.

**Comment by mgravell** [comment]
https://github.com/DapperLib/DapperAOT/releases/tag/1.0.16
