### ISSUE TITLE
DbString - analyzer and runtime

### ISSUE THREAD

**Issue by mgravell** [DapperLib/DapperAOT#89]
`DbString` is a Dapper type that allows metadata to be conveyed for string types.

However:

- it is allocatey
- it isn't touched by AOT today
- what it achieves is the same as [`DbValue]`](https://github.com/DapperLib/DapperAOT/blob/main/src/Dapper.AOT/DbValueAttribute.cs)

Suggestions:

1. we need to verify that `[DbValue]` allows the size and type to be conveyed into `DbParameter`
2. we should emit a warning to use `[DbValue]` instead
3. we should probably treat `DbString` as a recognized type, and configure things correctly
4. for this last, I would propose (if any `DbString` are encountered) writing a helper method into the output (we have some prior art that copies entire files into the output; that would be fine) with a method that takes a `DbParameter` and `DbString` (`global::` qualified) and does the right things:

- if the entire `DbString` is null, just set `Value` to `DbNull`
- set the size if appropriate
- set the type if appropriate
- set the value using `AsValue`, or a `(object)value.Value ?? DbNull` if easier

The reason we can't put this into the library is that we can't ref Dapper directly because of the Dapper/Dapper.StrongName duality - hence we need to implement it in codegen

**Comment by DeagleGross** [comment]
questions:
1) what does it mean "[[DbValue](https://github.com/DapperLib/DapperAOT/blob/main/src/Dapper.AOT/DbValueAttribute.cs)] allows the size and type to be conveyed into [DbParameter](https://learn.microsoft.com/en-us/dotnet/api/system.data.common.dbparameter?view=net-8.0)" (I can see both of them have `System.Data.DbType` member + `DbParameter` can handle strings (which `DbString` are))? Why is `DbParameter` in the context here?
2) where is the code that copies entire files into the output?

**Comment by mgravell** [comment]
1. when passing some member `.Foo` into the DB, we do that via a parameter; by default we can only guess as to the type and other properties - but sometimes the details matter, so this tribute allows the `.Size` and `.DbType` of the parameter object to be controlled more explicitly 

2 do you mean this? https://github.com/DapperLib/DapperAOT/blob/main/src/Dapper.AOT.Analyzers/CodeAnalysis/Writers/InterceptorsLocationAttributeWriter.cs#L24
